name: e_course_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  #ASSET
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.0
  flutter_svg: ^2.0.7
  
  #SHARED PREFERENCES
  shared_preferences: ^2.2.2

  #STATE MANAGERMENT
  get: ^4.6.6

  #INTL
  intl_utils: ^2.8.4
  flutter_localizations:
    sdk: flutter

  # FLUTTER TOAST
  fluttertoast: ^8.2.4

  # ANIMATION
  google_nav_bar: ^5.0.6
  smooth_page_indicator: ^1.1.0
  dots_indicator: ^3.0.0
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  image_picker: ^1.0.7

  # HTTP
  http: ^1.2.1
  dio: ^5.4.1
  jwt_decoder: ^2.0.1

  #DOTENV
  flutter_dotenv: ^5.1.0
  connectivity_plus: ^5.0.2

  #VIDEO PLAYER
  video_player: ^2.7.1
  chewie: ^1.7.1
  rxdart: ^0.27.7
  flutter_rating_bar: ^4.0.1

  #PIN CODE
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - lib/res/icons/
    - lib/res/images/
    - .env

flutter_intl:
  enabled: true
